#!/usr/bin/env ruby -w
# coding: utf-8

require 'rake/clean'
CLEAN.include 'take*.jpg'

task :default => :test

task :install do
  sh "pip3 install mediapipe"
  sh "pip3 install pyvirtualcam"
end

task :uninstallobs do
  sh "cd /Library/CoreMediaIO/Plug-Ins/DAL; sudo mv obs-mac-virtualcam.plugin .."
end

task :test do
  sh "ruby go.rb"
end
