#!/usr/bin/env ruby -w
# coding: utf-8
# Copyright (C) 2004-2021 Koichiro Eto, All rights reserved.
# License: BSD 3-Clause License

task :default => :test

task :cp do
  sh "cp /Users/eto/dev/fmod/extras/lib/libfmod.dylib /usr/local/lib"
end

task :test do
  sh "ruby test4.rb"
end
