#!/usr/bin/env ruby -w
# coding: utf-8

task :default => :test
task :install do
  sh "pip3 install mediapipe"
end
task :test do
  #sh "python3 -m venv mp_env && source mp_env/bin/activate"
  #sh "python3 test5.py"
  sh "ruby test4.rb"
end
