#!/usr/bin/env ruby -w
# coding: utf-8

task :default => :test
task :install do
  sh "pip3 install mediapipe"
end
task :uninstallobs do
  sh "cd /Library/CoreMediaIO/Plug-Ins/DAL; sudo mv obs-mac-virtualcam.plugin .."
end
task :test do
  #sh "python3 -m venv mp_env && source mp_env/bin/activate"
  #sh "python3 test5.py"
  sh "ruby test6.rb"
end
